In [10]:
import pandas as pd
df_listed = pd.read_csv("data/CRMLSListing202602.csv")
df_sold = pd.read_csv("data/CRMLSSold202602.csv")

In [26]:
df_listed.head(20)

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,599000.0,1155878924,NaN,NaN,Rhonda,Cudeback,33.846885,-118.189492,309 E Silva Street,Residential,...,2.0,False,1.0,Long Beach Unified,90805,NaN,0.0,2250.0,NaN,309 E Silva Street
1,699000.0,1155878603,NaN,NaN,Frances,Mouser,33.587219,-117.177790,27636 Brentstone Way,Residential,...,4.0,NaN,3.0,Murrieta,92563,NaN,0.0,8276.4,NaN,27636 Brentstone Way
2,1250000.0,1155878531,2026-03-24,1250000.0,Marcel,Bonee,33.162238,-117.260161,5086 Corinthia Way,Residential,...,NaN,False,2.0,NaN,92056,Allison James Estates & Homes,755.0,4309.0,NaN,5086 Corinthia Way
3,27000.0,1155877325,NaN,NaN,Georgie,Fenton,33.605898,-117.893620,203 Sapphire,ResidentialLease,...,0.0,False,2.0,Newport Mesa Unified,92662,NaN,0.0,2550.0,NaN,203 Sapphire
4,699000.0,1155873898,NaN,NaN,Ryan,Caron,32.696978,-117.009878,8773 Leigh Ave,Residential,...,NaN,NaN,2.0,Sweetwater Union,91977,NaN,0.0,5800.0,NaN,8773 Leigh Ave
5,2899000.0,1155873726,NaN,NaN,Rob,Depaoli,33.893323,-118.411866,448 23rd,Residential,...,2.0,False,2.0,Manhattan Unified,90266,NaN,0.0,2715.0,NaN,448 23rd
6,399000.0,1155871031,NaN,NaN,Annette,Garten,39.529567,-121.567992,6 Orangewood,ResidentialIncome,...,NaN,False,1.0,NaN,95965,NaN,0.0,6970.0,NaN,6 Orangewood
7,1349000.0,1155870845,NaN,NaN,Lauren,Luczyski,34.132167,-118.178722,524 Glen Holly Drive,Residential,...,NaN,False,2.0,NaN,91105,NaN,NaN,6767.0,NaN,524 Glen Holly Drive
8,750000.0,1155868238,NaN,NaN,Jimmy,Rashid,34.276961,-118.535806,11348 Reseda B,Residential,...,1.0,False,0.0,Los Angeles Unified,91326,NaN,0.0,7821.0,NaN,11348 Reseda B
9,1200000.0,1155868139,NaN,NaN,Nasheen,Noor,33.885573,-118.229051,420 W Tichenor Street,Residential,...,3.0,False,2.0,Compton Unified,90220,NaN,0.0,16755.0,NaN,420 W Tichenor Street
10,1998000.0,1155866218,NaN,NaN,Debbie,Neugebauer,33.709956,-118.027534,17372 Forbes,Residential,...,1.0,False,2.0,Huntington Beach Union High,92649,NaN,0.0,6004.0,NaN,17372 Forbes
11,749000.0,1155864458,NaN,NaN,Kyler,Hamann,35.902397,-120.446186,70331 Vineyard Canyon Rd.,Residential,...,4.0,False,2.0,Shandon Joint Unified,93451,NaN,0.0,378972.0,NaN,70331 Vineyard Canyon Rd.
12,1500000.0,1155861266,2026-03-24,1325000.0,Joe,Ghio,32.780798,-117.252157,811 Niantic Ct,Residential,...,NaN,False,0.0,NaN,92109,OUT OF AREA,NaN,NaN,NaN,811 Niantic Ct
13,14000.0,1155859617,2026-03-25,14000.0,Kimberly,Tucker,38.939488,-122.621034,16175 16175 23rd Ave,Land,...,NaN,False,NaN,NaN,95422,Century 21 Epic,0.0,4792.0,NaN,16175 16175 23rd Ave
14,15000.0,1155858714,NaN,NaN,Nicole,Coutee,34.242061,-117.251654,0 Chateau,Land,...,NaN,False,NaN,NaN,92325,NaN,0.0,6200.0,NaN,0 Chateau
15,4100000.0,1155857709,2026-03-25,3890000.0,Tyler,Polan,33.030122,-117.284498,1526 Rubenstein Ave.,Residential,...,1.0,NaN,2.0,San Dieguito Union,92007,Compass,0.0,10300.0,NaN,1526 Rubenstein Ave.
16,3398000.0,1155847850,NaN,NaN,Lucy,Li,33.691115,-117.753816,2 Conifer,Residential,...,1.0,False,3.0,Irvine Unified,92620,NaN,210.0,7431.0,NaN,2 Conifer
17,1338800.0,1155838079,NaN,NaN,Alison,Burns,34.162872,-117.493617,5017 Mandala Avenue,Residential,...,4.0,False,3.0,Chaffey Joint Union High,91739,NaN,0.0,749232000.0,NaN,5017 Mandala Avenue
18,750000.0,1155837776,NaN,NaN,Cynthia,Rorty,34.124340,-117.459491,7132 Niagara Drive,Residential,...,NaN,False,3.0,NaN,92336,NaN,NaN,7000.0,NaN,7132 Niagara Drive
19,849990.0,1155835292,NaN,NaN,Janette,Correa,34.196365,-118.580526,6947 Sunnybrae Avenue,Residential,...,2.0,False,2.0,Los Angeles Unified,91306,NaN,0.0,8080.0,NaN,6947 Sunnybrae Avenue

Pricing:
    Original List Price
    Close Price
Dates:
    Close Dates
Location:
    Latitude, Longitude
    Postal Code
    Unparsed Address
    High School District
Property Info:
    Type
    Garage Spaces
    Main Level Bedrooms
    Lost Size

In [19]:
df_listed.info()
df_listed.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10988 entries, 0 to 10987
Data columns (total 81 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OriginalListPrice             10937 non-null  float64
 1   ListingKey                    10988 non-null  int64
 2   CloseDate                     1573 non-null   object
 3   ClosePrice                    1199 non-null   float64
 4   ListAgentFirstName            10930 non-null  object
 5   ListAgentLastName             10987 non-null  object
 6   Latitude                      10844 non-null  float64
 7   Longitude                     10848 non-null  float64
 8   UnparsedAddress               10959 non-null  object
 9   PropertyType                  10988 non-null  object
 10  LivingArea                    9556 non-null   float64
 11  ListPrice                     10958 non-null  float64
 12  DaysOnMarket                  10988 non-null  int64
 13  ListOfficeName                10988 non-null  object
 14  BuyerOfficeName               1438 non-null   object
 15  CoListOfficeName              2265 non-null   object
 16  ListAgentFullName             10981 non-null  object
 17  CoListAgentFirstName          2257 non-null   object
 18  CoListAgentLastName           2264 non-null   object
 19  BuyerAgentMlsId               1441 non-null   object
 20  BuyerAgentFirstName           1442 non-null   object
 21  BuyerAgentLastName            1447 non-null   object
 22  FireplacesTotal               0 non-null      float64
 23  AssociationFeeFrequency       3407 non-null   object
 24  AboveGradeFinishedArea        0 non-null      float64
 25  ListingKeyNumeric             10988 non-null  int64
 26  MLSAreaMajor                  9951 non-null   object
 27  TaxAnnualAmount               68 non-null     float64
 28  CountyOrParish                10988 non-null  object
 29  PropertyType.1                10988 non-null  object
 30  MlsStatus                     10988 non-null  object
 31  ElementarySchool              1139 non-null   object
 32  ListAgentFirstName.1          10930 non-null  object
 33  AttachedGarageYN              7278 non-null   object
 34  ParkingTotal                  10292 non-null  float64
 35  BuilderName                   385 non-null    object
 36  PropertySubType               9595 non-null   object
 37  LotSizeAcres                  9994 non-null   float64
 38  SubdivisionName               3552 non-null   object
 39  BuyerOfficeAOR                1338 non-null   object
 40  YearBuilt                     10091 non-null  float64
 41  DaysOnMarket.1                10988 non-null  int64
 42  StreetNumberNumeric           10935 non-null  float64
 43  LivingArea.1                  9556 non-null   float64
 44  ListingId                     10988 non-null  object
 45  BathroomsTotalInteger         10019 non-null  float64
 46  City                          10982 non-null  object
 47  TaxYear                       17 non-null     float64
 48  BuildingAreaTotal             1622 non-null   float64
 49  BedroomsTotal                 9599 non-null   float64
 50  ContractStatusChangeDate      10869 non-null  object
 51  Longitude.1                   10848 non-null  float64
 52  ElementarySchoolDistrict      0 non-null      float64
 53  CoBuyerAgentFirstName         99 non-null     object
 54  PurchaseContractDate          3925 non-null   object
 55  ListingContractDate           10988 non-null  object
 56  BelowGradeFinishedArea        50 non-null     float64
 57  BusinessType                  98 non-null     object
 58  Latitude.1                    10844 non-null  float64
 59  ListPrice.1                   10958 non-null  float64
 60  StateOrProvince               10986 non-null  object
 61  CoveredSpaces                 0 non-null      float64
 62  MiddleOrJuniorSchool          1147 non-null   object
 63  FireplaceYN                   9333 non-null   object
 64  Stories                       8126 non-null   float64
 65  HighSchool                    1478 non-null   object
 66  Levels                        8879 non-null   object
 67  ListAgentLastName.1           10987 non-null  object
 68  CloseDate.1                   1573 non-null   object
 69  LotSizeDimensions             541 non-null    object
 70  LotSizeArea                   10037 non-null  float64
 71  MainLevelBedrooms             5459 non-null   float64
 72  NewConstructionYN             9427 non-null   object
 73  GarageSpaces                  9009 non-null   float64
 74  HighSchoolDistrict            6892 non-null   object
 75  PostalCode                    10988 non-null  object
 76  BuyerOfficeName.1             1438 non-null   object
 77  AssociationFee                7869 non-null   float64
 78  LotSizeSquareFeet             10023 non-null  float64
 79  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 80  UnparsedAddress.1             10959 non-null  object
dtypes: float64(31), int64(4), object(46)
memory usage: 6.8+ MB

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,1.093700e+04,1.098800e+04,1.199000e+03,10844.000000,10848.000000,9556.000000,1.095800e+04,10988.000000,0.0,0.0,...,10844.000000,1.095800e+04,0.0,8126.000000,1.003700e+04,5459.000000,9009.000000,7869.000000,1.002300e+04,0.0
mean,1.093359e+06,1.153754e+09,7.087059e+05,34.506758,-118.336753,1925.975084,1.044803e+06,11.679651,NaN,NaN,...,34.506758,1.044803e+06,NaN,1.362540,9.843527e+04,1.919582,1.701299,217.785209,3.420544e+05,NaN
std,4.847949e+06,5.028617e+05,1.131769e+06,1.665307,4.193899,1568.239424,2.059225e+06,11.511398,NaN,NaN,...,1.665307,2.059225e+06,NaN,0.480763,4.235864e+06,1.511874,1.173938,477.594108,1.033225e+07,NaN
min,1.450000e+00,1.153315e+09,4.250000e+02,0.000000,-124.144091,0.000000,1.450000e+00,-17.000000,NaN,NaN,...,0.000000,1.450000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,2.050000e+05,1.153428e+09,3.697500e+03,33.744210,-118.521115,1176.750000,2.102500e+05,4.000000,NaN,NaN,...,33.744210,2.102500e+05,NaN,1.000000,4.830000e+03,1.000000,1.000000,0.000000,5.269500e+03,NaN
50%,6.650000e+05,1.153588e+09,3.000000e+04,34.043860,-118.057300,1616.000000,6.601500e+05,9.000000,NaN,NaN,...,34.043860,6.601500e+05,NaN,1.000000,7.272000e+03,2.000000,2.000000,0.000000,7.560000e+03,NaN
75%,1.199900e+06,1.153792e+09,1.080000e+06,34.393931,-117.296743,2267.250000,1.199000e+06,19.000000,NaN,NaN,...,34.393931,1.199000e+06,NaN,2.000000,1.389800e+04,3.000000,2.000000,345.000000,1.774850e+04,NaN
max,4.595000e+08,1.155879e+09,9.980000e+06,41.891615,117.987980,59600.000000,8.200000e+07,415.000000,NaN,NaN,...,41.891615,8.200000e+07,NaN,2.000000,4.187423e+08,32.000000,23.000000,13751.000000,7.492320e+08,NaN

In [27]:
df_sold.head(20)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
1,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
3,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
4,Newport,Newport,NaN,False,NaN,NaN,False,525000.0,1155192177,2026-02-24,...,4.0,False,0.0,ABC Unified,94510,0.0,18730.0,NaN,CRMLS,CRMLS_CRM
5,Mrmls,SierraNorthValley,NaN,True,NaN,NaN,False,299000.0,1155179209,2026-02-27,...,2.0,False,1.0,Chico Unified,95926,468.0,871.0,NaN,CRMLS,CRMLS_CRM
6,CitrusValley,WestSanGabrielValley,NaN,False,NaN,NaN,False,905000.0,1155113968,2026-02-17,...,4.0,False,2.0,Pasadena Unified,91103,0.0,8251.0,NaN,CRMLS,CRMLS_CRM
7,BayEast,Oakland,Carpet,NaN,NaN,NaN,False,1210000.0,1155025463,2026-02-27,...,NaN,False,2.0,NaN,94598,NaN,27600.0,NaN,CRMLS,CRMLS_BMLS
8,Newport,Newport,"Tile,Wood",True,NaN,NaN,False,3150000.0,1154998305,2026-02-24,...,1.0,True,1.0,Newport Mesa Unified,92625,0.0,3540.0,NaN,CRMLS,CRMLS_CRM
9,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154943263,2026-02-24,...,NaN,False,2.0,Other,95032,NaN,10454.0,NaN,CRMLS,CRMLS_MLSL
10,NorthSanDiegoCounty,NorthSanDiegoCounty,Laminate,False,NaN,NaN,False,649999.0,1154868125,2026-02-27,...,NaN,NaN,1.0,San Diego Unified,92105,0.0,5500.0,NaN,CRMLS,CRMLS_CRP
11,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,True,NaN,NaN,NaN,700000.0,1154785403,2026-02-25,...,NaN,NaN,NaN,NaN,92070,0.0,3484800.0,NaN,CRMLS,CRMLS_CRP
12,SanDiego,PacificSouthwest,NaN,True,NaN,NaN,False,1191000.0,1154717602,2026-02-27,...,NaN,NaN,2.0,Other,91913,135.0,4356.0,NaN,CRMLS,CRMLS_CRP
13,Mrmls,PacificWest,NaN,True,NaN,NaN,True,510000.0,1154531404,2026-02-24,...,1.0,False,2.0,Lodi Unified,95219,479.0,6277.0,NaN,CRMLS,CRMLS_CRM
14,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,NaN,True,NaN,NaN,False,1500000.0,1154516228,2026-02-20,...,NaN,False,NaN,NaN,90069,2000.0,29660.0,NaN,CRMLS,CRMLS_CL
15,NaN,SanDiego,"Carpet,Tile",True,NaN,NaN,False,2425000.0,1154480605,2026-02-20,...,NaN,False,2.0,NaN,92127,227.0,7281.0,NaN,CRMLS,CRMLS_SAND
16,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,True,NaN,NaN,False,1600000.0,1154376266,2026-02-25,...,1.0,NaN,2.0,San Marcos Unified,92078,242.0,NaN,NaN,CRMLS,CRMLS_CRP
17,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154334545,2026-02-27,...,NaN,False,1.0,Other,95037,276.0,2240.0,NaN,CRMLS,CRMLS_MLSL
18,NaN,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154334544,2026-02-27,...,NaN,False,1.0,Other,94025,NaN,5900.0,NaN,CRMLS,CRMLS_MLSL
19,SouthwestRiversideCounty,SouthwestRiversideCounty,"Carpet,Tile",True,NaN,NaN,False,1199999.0,1154329704,2026-02-27,...,1.0,False,3.0,Saddleback Valley Unified,92688,87.0,5000.0,NaN,CRMLS,CRMLS_CRM

In [23]:
df_sold.info()
df_sold.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19069 entries, 0 to 19068
Data columns (total 79 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BuyerAgentAOR                 17550 non-null  object
 1   ListAgentAOR                  19064 non-null  object
 2   Flooring                      10943 non-null  object
 3   ViewYN                        17234 non-null  object
 4   WaterfrontYN                  17 non-null     object
 5   BasementYN                    294 non-null    object
 6   PoolPrivateYN                 16978 non-null  object
 7   OriginalListPrice             19005 non-null  float64
 8   ListingKey                    19069 non-null  int64
 9   CloseDate                     19069 non-null  object
 10  ClosePrice                    19067 non-null  float64
 11  ListAgentFirstName            19008 non-null  object
 12  ListAgentLastName             19067 non-null  object
 13  Latitude                      18864 non-null  float64
 14  Longitude                     18880 non-null  float64
 15  UnparsedAddress               19044 non-null  object
 16  PropertyType                  19069 non-null  object
 17  LivingArea                    17658 non-null  float64
 18  ListPrice                     19038 non-null  float64
 19  DaysOnMarket                  19069 non-null  int64
 20  ListOfficeName                19069 non-null  object
 21  BuyerOfficeName               18893 non-null  object
 22  CoListOfficeName              4023 non-null   object
 23  ListAgentFullName             19049 non-null  object
 24  CoListAgentFirstName          4008 non-null   object
 25  CoListAgentLastName           4019 non-null   object
 26  BuyerAgentMlsId               18981 non-null  object
 27  BuyerAgentFirstName           18994 non-null  object
 28  BuyerAgentLastName            19050 non-null  object
 29  FireplacesTotal               0 non-null      float64
 30  AssociationFeeFrequency       5708 non-null   object
 31  AboveGradeFinishedArea        0 non-null      float64
 32  ListingKeyNumeric             19069 non-null  int64
 33  MLSAreaMajor                  17083 non-null  object
 34  TaxAnnualAmount               75 non-null     float64
 35  CountyOrParish                19069 non-null  object
 36  MlsStatus                     19069 non-null  object
 37  ElementarySchool              1867 non-null   object
 38  AttachedGarageYN              13454 non-null  object
 39  ParkingTotal                  18457 non-null  float64
 40  BuilderName                   782 non-null    object
 41  PropertySubType               17591 non-null  object
 42  LotSizeAcres                  17312 non-null  float64
 43  SubdivisionName               6866 non-null   object
 44  BuyerOfficeAOR                17455 non-null  object
 45  YearBuilt                     18196 non-null  float64
 46  StreetNumberNumeric           19030 non-null  float64
 47  ListingId                     19069 non-null  object
 48  BathroomsTotalInteger         18164 non-null  float64
 49  City                          19061 non-null  object
 50  TaxYear                       15 non-null     float64
 51  BuildingAreaTotal             2650 non-null   float64
 52  BedroomsTotal                 17747 non-null  float64
 53  ContractStatusChangeDate      19069 non-null  object
 54  ElementarySchoolDistrict      0 non-null      float64
 55  CoBuyerAgentFirstName         1617 non-null   object
 56  PurchaseContractDate          18651 non-null  object
 57  ListingContractDate           19066 non-null  object
 58  BelowGradeFinishedArea        96 non-null     float64
 59  BusinessType                  58 non-null     object
 60  StateOrProvince               19069 non-null  object
 61  CoveredSpaces                 0 non-null      float64
 62  MiddleOrJuniorSchool          1858 non-null   object
 63  FireplaceYN                   17382 non-null  object
 64  Stories                       15505 non-null  float64
 65  HighSchool                    2463 non-null   object
 66  Levels                        16747 non-null  object
 67  LotSizeDimensions             1030 non-null   object
 68  LotSizeArea                   17401 non-null  float64
 69  MainLevelBedrooms             10259 non-null  float64
 70  NewConstructionYN             16756 non-null  object
 71  GarageSpaces                  16436 non-null  float64
 72  HighSchoolDistrict            12432 non-null  object
 73  PostalCode                    19063 non-null  object
 74  AssociationFee                13341 non-null  float64
 75  LotSizeSquareFeet             17380 non-null  float64
 76  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 77  OriginatingSystemName         19069 non-null  object
 78  OriginatingSystemSubName      19069 non-null  object
dtypes: float64(27), int64(3), object(49)
memory usage: 11.5+ MB

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,1.900500e+04,1.906900e+04,1.906700e+04,18864.000000,18880.000000,17658.000000,1.903800e+04,19069.000000,0.0,0.0,...,0.0,96.00000,0.0,15505.000000,1.740100e+04,10259.000000,16436.000000,13341.000000,1.738000e+04,0.0
mean,9.318530e+05,1.144714e+09,7.902909e+05,34.471614,-118.377412,1811.445526,8.013428e+05,53.007552,NaN,NaN,...,NaN,76.37500,NaN,1.364012,4.011186e+04,1.883712,1.719031,193.825314,7.408435e+05,NaN
std,7.366447e+06,1.425746e+07,1.160030e+06,1.605648,3.403870,1469.429226,1.236693e+06,74.095005,NaN,NaN,...,NaN,288.55379,NaN,0.481167,3.770824e+05,1.401134,1.290377,390.192133,4.343096e+07,NaN
min,1.000000e+00,4.258358e+08,0.000000e+00,0.000000,-123.809284,0.000000,2.000000e+00,-14.000000,NaN,NaN,...,NaN,0.00000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,1.150000e+04,1.145129e+09,1.050000e+04,33.727990,-118.501964,1158.000000,1.100000e+04,9.000000,NaN,NaN,...,NaN,0.00000,NaN,1.000000,4.808000e+03,1.000000,1.000000,0.000000,5.210750e+03,NaN
50%,5.990000e+05,1.149803e+09,5.850000e+05,34.029493,-118.026767,1564.000000,5.909950e+05,27.000000,NaN,NaN,...,NaN,0.00000,NaN,1.000000,7.001000e+03,2.000000,2.000000,0.000000,7.360000e+03,NaN
75%,1.000000e+06,1.151170e+09,1.000000e+06,34.261436,-117.301645,2151.000000,9.990000e+05,73.000000,NaN,NaN,...,NaN,0.00000,NaN,2.000000,1.192400e+04,3.000000,2.000000,320.000000,1.393900e+04,NaN
max,5.898880e+08,1.155696e+09,4.000000e+07,41.721840,118.140030,94619.000000,4.950000e+07,2094.000000,NaN,NaN,...,NaN,2031.00000,NaN,2.000000,2.895041e+07,32.000000,52.000000,9993.000000,5.193920e+09,NaN